services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - "--entryPoints.websecure.http.tls.certResolver=${ENVIRONMENT}"
      - "--certificatesResolvers.production.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesResolvers.local.acme.email=${LETSENCRYPT_EMAIL}"
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
      - "certs:/certs"
      - "./traefik.yml:/etc/traefik/traefik.yml"
    env_file:
      - .env
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true

volumes:
  letsencrypt:
  certs:
