services:
  traefik:
    image: traefik:v2.9
    restart: always
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yaml:/traefik.yaml:ro"
      - "./conf/:/etc/traefik/conf"
      - "./shared/:/shared"
    networks:
      - proxy

networks:
  proxy:
    external: true
