api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false
    network: "proxy-network"

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/self-signed.crt"
        keyFile: "/certs/self-signed.key"
