entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: default  # Usado para Let's Encrypt em produção

# Habilitar a dashboard do Traefik
api:
  dashboard: true
  insecure: true  # Permitir acesso à dashboard sem autenticação (não recomendado para produção)

# Providers para usar Docker como source
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "proxy-network"

# Resolvers para Let's Encrypt em produção
certificatesResolvers:
  default:
    acme:
      email: ${LETSENCRYPT_EMAIL}
      storage: /letsencrypt/acme.json
      tlsChallenge: true

# Certificados autoassinados dinâmicos para desenvolvimento
tls:
  options:
    default:
      selfSigned: true  # Gera certificados autoassinados em desenvolvimento
