entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: default  # Usado para Let's Encrypt em produção

# Habilitar a dashboard do Traefik
api:
  dashboard: true
  insecure: true  # Permitir acesso à dashboard sem autenticação (não recomendado para produção)

# Providers para usar Docker como source
providers:
  docker:
    exposedByDefault: false
    network: "proxy-network"

# Resolvers para Let's Encrypt em produção
certificatesResolvers:
  letsencrypt:
    acme:
      email: ${LETSENCRYPT_EMAIL}
      storage: /letsencrypt/acme.json
      tlsChallenge: true

  local:
    acme:
      email: "${LETSENCRYPT_EMAIL}"  # Email só para consistência
      storage: "/letsencrypt/acme.json"  # O arquivo onde os certificados locais serão armazenados
      tlsChallenge: true  # Desafio TLS para ambiente local (gera o autoassinado automaticamente)

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/ssl/certs/local.crt"  # Certificado padrão (opcional, pode ser gerado automaticamente)
        keyFile: "/etc/ssl/private/local.key"
