# Habilitar a dashboard do Traefik
api:
  dashboard: true
  insecure: true  # Permitir acesso à dashboard sem autenticação (não recomendado para produção)

# Providers para usar Docker como source
providers:
  docker:
    exposedByDefault: false
    network: "proxy-network"

entryPoints:
  websecure:
    address: ":443"

# Resolvers para Let's Encrypt em produção
certificatesResolvers:
  production:
    acme:
      tlsChallenge: true
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: "web"

  local:
    acme:
      storage: "/letsencrypt/acme.json"  # O arquivo onde os certificados locais serão armazenados
      tlsChallenge: true  # Desafio TLS para ambiente local (gera o autoassinado automaticamente)

log:
  level: DEBUG